### ISSUE TITLE
What first features we want to put in the Kanban ?

### ISSUE THREAD

**Issue by AlexandreBillereau** [AlexandreBillereau/GameBoomBoom#4]
what i want to do
-  a player and movement
-  debug mode
- camera tracking

**Comment by DrainGK** [comment]
The first things to do in my eyes:

- Project setup
- Player movement
- Input Manager
- Dungeon generator 

Little amount of code and it's the base for the game.

then we can add the second phase:
- Dash
- Attack
- Enemy
- Enemy generator
- Enemy Killed
- Health

phase three:

- Type enemy
- Type player
- Strength and weakness
- Bonus

Please, feel free to complete!
